package eu.spitfire_project.ld4s.vocabulary;

/* CVS $Id: $ */
 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from /Users/Kunal/Documents/workspace/ld4s/sensor.rdf 
 * @author Auto-generated by schemagen on 05 Aug 2014 15:46 
 */
public class EQIQVocab {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://eqiq.techlabs.accenture.com/sensor#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final DatatypeProperty altitude = m_model.createDatatypeProperty( "http://eqiq.techlabs.accenture.com/sensor#altitude" );
    
    public static final DatatypeProperty apiResponseCode = m_model.createDatatypeProperty( "http://eqiq.techlabs.accenture.com/sensor#apiResponseCode" );
    
    public static final DatatypeProperty apikey = m_model.createDatatypeProperty( "http://eqiq.techlabs.accenture.com/sensor#apikey" );
    
    public static final DatatypeProperty data_access_url = m_model.createDatatypeProperty( "http://eqiq.techlabs.accenture.com/sensor#data_access_url" );
    
    public static final DatatypeProperty deviceID = m_model.createDatatypeProperty( "http://eqiq.techlabs.accenture.com/sensor#deviceID" );
    
    public static final DatatypeProperty deviceName = m_model.createDatatypeProperty( "http://eqiq.techlabs.accenture.com/sensor#deviceName" );
    
    public static final DatatypeProperty double_datatype = m_model.createDatatypeProperty( "http://eqiq.techlabs.accenture.com/sensor#double_datatype" );
    
    public static final DatatypeProperty hasLocation = m_model.createDatatypeProperty( "http://eqiq.techlabs.accenture.com/sensor#hasLocation" );
    
    public static final DatatypeProperty int_datatype = m_model.createDatatypeProperty( "http://eqiq.techlabs.accenture.com/sensor#int_datatype" );
    
    public static final DatatypeProperty isProcessLevel = m_model.createDatatypeProperty( "http://eqiq.techlabs.accenture.com/sensor#isProcessLevel" );
    
    public static final DatatypeProperty latitude = m_model.createDatatypeProperty( "http://eqiq.techlabs.accenture.com/sensor#latitude" );
    
    public static final DatatypeProperty long_datatype = m_model.createDatatypeProperty( "http://eqiq.techlabs.accenture.com/sensor#long_datatype" );
    
    public static final DatatypeProperty longitude = m_model.createDatatypeProperty( "http://eqiq.techlabs.accenture.com/sensor#longitude" );
    
    public static final DatatypeProperty sensorID = m_model.createDatatypeProperty( "http://eqiq.techlabs.accenture.com/sensor#sensorID" );
    
    public static final DatatypeProperty sensorName = m_model.createDatatypeProperty( "http://eqiq.techlabs.accenture.com/sensor#sensorName" );
    
    public static final DatatypeProperty timestamp = m_model.createDatatypeProperty( "http://eqiq.techlabs.accenture.com/sensor#timestamp" );
    
    public static final DatatypeProperty unitType = m_model.createDatatypeProperty( "http://eqiq.techlabs.accenture.com/sensor#unitType" );
    
    public static final OntProperty deviceType = m_model.createOntProperty( "http://eqiq.techlabs.accenture.com/sensor#deviceType" );
    
    public static final OntProperty hasSensors = m_model.createOntProperty( "http://eqiq.techlabs.accenture.com/sensor#hasSensors" );
    
    public static final OntProperty hasUOM = m_model.createOntProperty( "http://eqiq.techlabs.accenture.com/sensor#hasUOM" );
    
    public static final OntProperty location_datatype = m_model.createOntProperty( "http://eqiq.techlabs.accenture.com/sensor#location_datatype" );
    
    public static final OntProperty observesReading = m_model.createOntProperty( "http://eqiq.techlabs.accenture.com/sensor#observesReading" );
    
    public static final OntClass APICall = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#APICall" );
    
    public static final OntClass APICallSensor = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#APICallSensor" );
    
    public static final OntClass Apigee = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#Apigee" );
    
    public static final OntClass BMCPatrol = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#BMCPatrol" );
    
    public static final OntClass CPUReading = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#CPUReading" );
    
    public static final OntClass Device = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#Device" );
    
    public static final OntClass DiskReading = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#DiskReading" );
    
    public static final OntClass Location = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#Location" );
    
    public static final OntClass LocationReading = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#LocationReading" );
    
    public static final OntClass MemoryReading = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#MemoryReading" );
    
    public static final OntClass ObservationData = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#ObservationData" );
    
    public static final OntClass Sensor = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#Sensor" );
    
    public static final OntClass UOM = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#UOM" );
    
    public static final OntClass VCenter = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#VCenter" );
    
    public static final OntClass VMSensor = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#VMSensor" );
    
    public static final OntClass bytes_per_second = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#bytes_per_second" );
    
    public static final OntClass percentage = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#percentage" );
    
    public static final OntClass size_in_GB = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#size_in_GB" );
    
    public static final OntClass size_in_MB = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#size_in_MB" );
    
    public static final OntClass time_in_millisec = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#time_in_millisec" );
    
    public static final OntClass uom_location = m_model.createClass( "http://eqiq.techlabs.accenture.com/sensor#uom_location" );
    
    public static final Individual APICallLatency = m_model.createIndividual( "http://eqiq.techlabs.accenture.com/sensor#APICallLatency", APICall );
    
    public static final Individual Apigee_1 = m_model.createIndividual( "http://eqiq.techlabs.accenture.com/sensor#Apigee_1", Apigee );
    
    public static final Individual BMCPatrol_1 = m_model.createIndividual( "http://eqiq.techlabs.accenture.com/sensor#BMCPatrol_1", BMCPatrol );
    
    public static final Individual BizApp_1 = m_model.createIndividual( "http://eqiq.techlabs.accenture.com/sensor#BizApp_1", m_model.createClass( "http://eqiq.techlabs.accenture.com/app#BizApp" ) );
    
    public static final Individual LocationReading_1 = m_model.createIndividual( "http://eqiq.techlabs.accenture.com/sensor#LocationReading_1", LocationReading );
    
    public static final Individual VCenter_1 = m_model.createIndividual( "http://eqiq.techlabs.accenture.com/sensor#VCenter_1", VCenter );
    
    public static final Individual cpu_usage = m_model.createIndividual( "http://eqiq.techlabs.accenture.com/sensor#cpu_usage", CPUReading );
    
    public static final Individual disk_usage_bps = m_model.createIndividual( "http://eqiq.techlabs.accenture.com/sensor#disk_usage_bps", DiskReading );
    
    public static final Individual memory_usage_in_MB = m_model.createIndividual( "http://eqiq.techlabs.accenture.com/sensor#memory_usage_in_MB", MemoryReading );
    
}
